name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.0
      with:
        node-version: 20.x

    # Instalar dependências Yarn
    - name: Install dependencies
      run: yarn

    # Executar build
    - name: Run build
      run: yarn build
    
    # Copiar pasta dist para dentro da Digital Ocean
    - name: Copy dist to Digital Ocean
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: 22
        key: ${{ secrets.SSH_KEY }}
        source: "dist"
        target: "test"

    # Substituir o código da pasta dist pelo novo código
    # Executar "yarn" na Digital Ocean
    # Executar as migrations
    # Restart no servidor Node.js
